-- ============================================================================
-- 03_STAGING.SQL — Generate synthetic data for Digital Islamic Banking Intelligence
-- Country: MALAYSIA | Currency: MYR
-- ============================================================================
USE DATABASE ISLAMIC_DIGITAL_BANKING;
USE SCHEMA RAW;

-- Data generation scripts are demo-specific.
-- See the handcrafted SQL in the aws-malaysia-semiconductor-yield demo for
-- the full pattern: GENERATOR + UNIFORM + LATERAL for distribution,
-- Cortex Complete for text generation, engineered key demo numbers.

-- Target row counts:
-- TRANSACTIONS: 2,000,000 rows — Monthly Islamic banking transactions (transfers, payments, financing)
-- ACCOUNTS: 100,000 rows — Digital Islamic bank customer accounts
-- ALERTS: 5,000 rows — Fraud and AML alerts generated by ML models
-- PRODUCTS: 50 rows — Shariah-compliant digital banking products (savings, financing, investment)
-- CUSTOMER_FEEDBACK: 20,000 rows — App store reviews, in-app feedback, and NPS responses
