-- Generated from generator/demo_specs/aws-malaysia-islamic-finance-digital.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-malaysia-islamic-finance-digital
-- This is the schema that is actually deployed for MY_ISLAMIC_FINANCE_DIGITAL.

-- Alerts fire on the bottom tail of Products
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_PRODUCTS) AS T
  FROM RAW.TRANSACTIONS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_PRODUCTS <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_PRODUCTS), 2) AS AVG_PRODUCTS,
  ROUND(AVG(f.KPI_CONVERSION), 2) AS AVG_CONVERSION,
  ROUND(AVG(f.KPI_AVG_INVESTMENT), 2) AS AVG_INVESTMENT,
  ROUND(AVG(f.KPI_SHARIAH_COMPLIANCE), 2) AS AVG_SHARIAH_COMPLIANCE
FROM RAW.TRANSACTIONS f
JOIN RAW.PRODUCTS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_PRODUCTS), 2) AS AVG_PRODUCTS,
  ROUND(AVG(f.KPI_CONVERSION), 2) AS AVG_CONVERSION,
  ROUND(AVG(f.KPI_AVG_INVESTMENT), 2) AS AVG_INVESTMENT,
  ROUND(AVG(f.KPI_SHARIAH_COMPLIANCE), 2) AS AVG_SHARIAH_COMPLIANCE
FROM RAW.TRANSACTIONS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_SHARIAH_COMPLIANCE) AS KPI_SHARIAH_COMPLIANCE, AVG(KPI_PRODUCTS) AS KPI_PRODUCTS, AVG(KPI_CONVERSION) AS KPI_CONVERSION, AVG(KPI_AVG_INVESTMENT) AS KPI_AVG_INVESTMENT FROM RAW.TRANSACTIONS),
     en AS (SELECT SUM(KPI_DIGITAL_ISLAMIC_AUM) AS KPI_DIGITAL_ISLAMIC_AUM, SUM(KPI_ACTIVE_USERS) AS KPI_ACTIVE_USERS, SUM(KPI_APP_DAU) AS KPI_APP_DAU FROM RAW.PRODUCTS)
  SELECT 1 AS SORT_ORDER, 'Digital Islamic AUM' AS TITLE, KPI_DIGITAL_ISLAMIC_AUM AS VALUE_NUM, 'RM' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_DIGITAL_ISLAMIC_AUM) / 1000000000), 1) AS DECIMAL(38,1))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Active Users' AS TITLE, KPI_ACTIVE_USERS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_ACTIVE_USERS) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Shariah Compliance' AS TITLE, KPI_SHARIAH_COMPLIANCE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SHARIAH_COMPLIANCE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Products' AS TITLE, KPI_PRODUCTS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PRODUCTS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'App DAU' AS TITLE, KPI_APP_DAU AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_APP_DAU) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Conversion' AS TITLE, KPI_CONVERSION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CONVERSION)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Avg Investment' AS TITLE, KPI_AVG_INVESTMENT AS VALUE_NUM, 'RM' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_AVG_INVESTMENT) / 1000), 1) AS DECIMAL(38,1))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
