-- Arrears escalation risk scoring and arrears-volume forecast over the synthetic snapshot.
-- Predicts P(an arrears case on the portfolio is escalated to restructuring review in the next 7 days)
-- per portfolio and reports out-of-time holdout metrics; nothing is seeded as a prediction.
USE DATABASE IDENTIFIER($DEMO_DB);
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE VIEW ML.ESCALATION_FEATURES AS
SELECT r.ENTITY_ID, r.EVENT_DATE, a.CATEGORY, a.RISK_TIER, a.PORTFOLIO_AGE_YEARS,
       r.AUTODEBIT_REJECT_PCT, r.AVG_DAYS_PAST_DUE,
       AVG(r.AUTODEBIT_REJECT_PCT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS AUTODEBIT_REJECT_7D,
       SUM(r.ESCALATED_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS ESCALATED_30D,
       IFF(SUM(r.ESCALATED_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) > 0,
           'ESCALATED', 'OK') AS LABEL,
       COUNT(*) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) AS FUTURE_DAYS
FROM RAW.PORTFOLIO_DAILY r JOIN RAW.PORTFOLIOS a ON a.ID = r.ENTITY_ID
-- City-wide payment channel disruptions are not portfolio-driven, so they are excluded from training.
WHERE r.ARREARS_REASON <> 'Payment channel disruption';

-- Time-based split: train on older labelled days, hold out the most recent 14 labelled days.
CREATE VIEW ML.ESCALATION_TRAIN AS
SELECT CATEGORY, RISK_TIER, PORTFOLIO_AGE_YEARS, AUTODEBIT_REJECT_PCT, AVG_DAYS_PAST_DUE, AUTODEBIT_REJECT_7D, ESCALATED_30D, LABEL
FROM ML.ESCALATION_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE < DATEADD('day', -21, CURRENT_DATE());

CREATE VIEW ML.ESCALATION_HOLDOUT AS
SELECT ENTITY_ID, EVENT_DATE, CATEGORY, RISK_TIER, PORTFOLIO_AGE_YEARS, AUTODEBIT_REJECT_PCT, AVG_DAYS_PAST_DUE, AUTODEBIT_REJECT_7D, ESCALATED_30D, LABEL
FROM ML.ESCALATION_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE >= DATEADD('day', -21, CURRENT_DATE());

CREATE SNOWFLAKE.ML.CLASSIFICATION ML.ESCALATION_RISK_MODEL(
  INPUT_DATA => TABLE(ML.ESCALATION_TRAIN),
  TARGET_COLNAME => 'LABEL'
);

-- Out-of-time holdout: precision/recall at 0.5 versus the base rate.
CREATE TABLE ML.ESCALATION_RISK_HOLDOUT_METRICS AS
WITH scored AS (
  SELECT LABEL, ML.ESCALATION_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'RISK_TIER', RISK_TIER, 'PORTFOLIO_AGE_YEARS', PORTFOLIO_AGE_YEARS,
           'AUTODEBIT_REJECT_PCT', AUTODEBIT_REJECT_PCT, 'AVG_DAYS_PAST_DUE', AVG_DAYS_PAST_DUE,
           'AUTODEBIT_REJECT_7D', AUTODEBIT_REJECT_7D, 'ESCALATED_30D', ESCALATED_30D)):probability:ESCALATED::FLOAT AS P
  FROM ML.ESCALATION_HOLDOUT
)
SELECT COUNT(*) AS N,
       AVG(IFF(LABEL = 'ESCALATED', 1, 0)) AS BASE_RATE,
       SUM(IFF(P >= 0.5 AND LABEL = 'ESCALATED', 1, 0)) / NULLIF(SUM(IFF(P >= 0.5, 1, 0)), 0) AS PRECISION_AT_50,
       SUM(IFF(P >= 0.5 AND LABEL = 'ESCALATED', 1, 0)) / NULLIF(SUM(IFF(LABEL = 'ESCALATED', 1, 0)), 0) AS RECALL_AT_50,
       CURRENT_TIMESTAMP() AS EVALUATED_AT
FROM scored;

-- Latest-day score per portfolio (label unknown, so excluded from features).
CREATE TABLE ML.ESCALATION_RISK_SCORES AS
WITH latest AS (
  SELECT * FROM ML.ESCALATION_FEATURES
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ENTITY_ID ORDER BY EVENT_DATE DESC) = 1
), scored AS (
  SELECT ENTITY_ID, EVENT_DATE,
         ML.ESCALATION_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'RISK_TIER', RISK_TIER, 'PORTFOLIO_AGE_YEARS', PORTFOLIO_AGE_YEARS,
           'AUTODEBIT_REJECT_PCT', AUTODEBIT_REJECT_PCT, 'AVG_DAYS_PAST_DUE', AVG_DAYS_PAST_DUE,
           'AUTODEBIT_REJECT_7D', AUTODEBIT_REJECT_7D, 'ESCALATED_30D', ESCALATED_30D)) AS P
  FROM latest
)
SELECT ENTITY_ID, EVENT_DATE AS SCORED_AS_OF,
       ROUND(P:probability:ESCALATED::FLOAT, 4) AS ESCALATION_PROB_7D,
       CASE WHEN P:probability:ESCALATED::FLOAT >= 0.5 THEN 'High'
            WHEN P:probability:ESCALATED::FLOAT >= 0.25 THEN 'Medium' ELSE 'Low' END AS RISK_BAND,
       CURRENT_TIMESTAMP() AS SCORED_AT
FROM scored;

-- Bank-wide arrears-volume forecast (14 days) from the daily series, for collections staffing.
CREATE VIEW ML.DAILY_ARREARS AS
SELECT EVENT_DATE::TIMESTAMP_NTZ AS TS, SUM(ARREARS_COUNT)::FLOAT AS ARREARS_COUNT
FROM RAW.PORTFOLIO_DAILY GROUP BY EVENT_DATE;

CREATE SNOWFLAKE.ML.FORECAST ML.ARREARS_FORECAST_MODEL(
  INPUT_DATA => TABLE(ML.DAILY_ARREARS),
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'ARREARS_COUNT'
);

CREATE TABLE ML.ARREARS_FORECAST AS
SELECT TS::DATE AS FORECAST_DATE, GREATEST(0, FORECAST) AS ARREARS_COUNT,
       GREATEST(0, LOWER_BOUND) AS LOWER_BOUND, UPPER_BOUND
FROM TABLE(ML.ARREARS_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));
