-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Digital Islamic Banking Intelligence
-- ============================================================================
USE DATABASE ISLAMIC_DIGITAL_BANKING;
USE SCHEMA ML;

-- ML.ANOMALY_DETECTION: TRANSACTION_FRAUD_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.TRANSACTION_FRAUD_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.TRANSACTION_METRICS'),
  SERIES_COLNAME => 'ACCOUNT_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'TXN_AMOUNT',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.TRANSACTION_FRAUD_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.TRANSACTION_FRAUD_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.TRANSACTION_METRICS'), SERIES_COLNAME => 'ACCOUNT_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'TXN_AMOUNT'));

-- ML.CLASSIFICATION: CUSTOMER_SEGMENT_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION ML.CUSTOMER_SEGMENT_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.CUSTOMER_SEGMENTS'),
  TARGET_COLNAME => 'SEGMENT_LABEL'
);

