-- ============================================================================
-- 99_RESET.SQL — Reset Digital Islamic Banking Intelligence to clean demo state
-- ============================================================================
USE DATABASE ISLAMIC_DIGITAL_BANKING;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_SCORE_TRANSACTIONS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SEGMENT_CUSTOMERS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_GENERATE_OFFERS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.TRANSACTION_METRICS REFRESH;
ALTER DYNAMIC TABLE CURATED.FRAUD_ALERTS_LIVE REFRESH;
ALTER DYNAMIC TABLE CURATED.CUSTOMER_SEGMENTS REFRESH;
ALTER DYNAMIC TABLE CURATED.PRODUCT_PERFORMANCE REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM ISLAMIC_DIGITAL_BANKING.RAW.TRANSACTIONS → 2000000
-- SELECT COUNT(*) FROM ISLAMIC_DIGITAL_BANKING.RAW.ACCOUNTS → 100000
-- SELECT COUNT(*) FROM ISLAMIC_DIGITAL_BANKING.RAW.CUSTOMER_FEEDBACK → 20000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_GENERATE_OFFERS RESUME;
ALTER TASK IF EXISTS APP.TASK_SEGMENT_CUSTOMERS RESUME;
ALTER TASK IF EXISTS APP.TASK_SCORE_TRANSACTIONS RESUME;
